apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lens-selector-example.fullname" . }}
  labels:
    {{- include "lens-selector-example.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  {{- range $key, $value := .Values.config.extraConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
